package com.praveen.demosecurity.controller;

import com.praveen.demosecurity.model.Student;
import jakarta.servlet.http.HttpServletRequest;
import org.springframework.security.web.csrf.CsrfToken;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RestController;

import java.util.ArrayList;
import java.util.List;

@RestController
public class StudentController {

    private Student student;

    private List<Student> students = new ArrayList<>(List.of(
            new Student(1,"Praveen",90),
            new Student(2,"Vinit",70)
    ));

    @GetMapping("/csrf-token")
    public CsrfToken getToken(HttpServletRequest request){
        return (CsrfToken) request.getAttribute("_csrf");
    }
//    A CSRF token (Cross-Site Request Forgery token) is a unique, secret,and unpredictable value generated by a web server
//    and included in web pages/forms to protect against CSRF attacks.
//    Embedded in every form/request that makes changes on the server (e.g., POST, PUT).

    @GetMapping("/students")
    public List<Student> getStudents(){
        return students;
    }

    @PostMapping("/students")
    public Student addStudent(@RequestBody Student student){
        students.add(student);
        return student;
    }


}
